jobs:
  - name: mohit-1
    type: manifest
    on_success:
      - script: echo 'this is a success'
      #- NOTIFY: slackNotification
      #- NOTIFY: myEmail
      #- NOTIFY: hipchat
      #- NOTIFY: irc
    on_start:
      #- NOTIFY: slackNotification
      #- NOTIFY: hipchat
      #- NOTIFY: irc
    steps:
      - IN: box-nginx
      - IN: trigger-dv-man

  - name: mohit-2
    type: manifest
    steps:
      - IN: box-sn
      - IN: trigger-dv-man
